### ISSUE TITLE
Leaks MAC addresses to https://mac-to-vendor.herokuapp.com

### ISSUE THREAD

**Issue by hdm** [iamrootsh3ll/AnchorWatch#2] opened 2019-03-11 20:54 UTC
The current script sends every seen MAC address to a Heroku instance. This might be a privacy issue. You might consider embedding a generated array of MAC->Vendor mappings into the PS script directly. A couple consolidated datasets you can use are:
* https://github.com/hdm/deepmac-tracker
* https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf

**Comment by iamrootsh3ll** [comment] 2019-03-11 21:06
Thanks for raising this issue and providing with helpful resources.

I am actually working on using the OUI list offline. But, never thought on the privacy side of this. Thanks for the awareness HD!

**Comment by iamrootsh3ll** [comment] 2019-03-11 22:47
The issue is now fixed. closing.

**Closed as completed** 2019-03-11 22:48 UTC
